import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const tplRoot = path.join(root, 'templates')
const readmePath = path.join(root, 'README.md')
const MARK_START = '<!-- gallery:start -->'
const MARK_END = '<!-- gallery:end -->'
const COVER_H = 200
const LINK_STYLE = 'text-decoration:none;color:inherit;'
const FRAME_STYLE = 'display:inline-block;padding:8px;background:#eaeef2;border:1px solid #d0d7de;border-radius:4px;box-shadow:0 2px 6px rgba(27,31,36,.12);line-height:0;'
const IMG_STYLE = `display:block;height:${COVER_H}px;width:auto;border-radius:2px;background:#fff;`

function escHtml(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function readMeta(dir) {
  const p = path.join(dir, 'meta.json')
  if (!fs.existsSync(p)) return null
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8')) || {}
  } catch {
    return null
  }
}

function hasPack(dir) {
  if (fs.existsSync(path.join(dir, 'template.pdfdog'))) return true
  let hits = []
  try {
    hits = fs.readdirSync(dir).filter((n) => n.toLowerCase().endsWith('.pdfdog'))
  } catch {
    return false
  }
  return hits.length === 1
}

function listTemplates() {
  if (!fs.existsSync(tplRoot)) return []
  let names = []
  try {
    names = fs.readdirSync(tplRoot)
  } catch {
    return []
  }

  const out = []
  for (const id of names) {
    const dir = path.join(tplRoot, id)
    let st
    try {
      st = fs.statSync(dir)
    } catch {
      continue
    }
    if (!st.isDirectory()) continue

    const meta = readMeta(dir)
    if (!meta || meta.hidden === true) continue
    if (!hasPack(dir)) continue
    if (!fs.existsSync(path.join(dir, 'cover.png'))) continue

    out.push({
      id,
      name: String(meta.name || id),
      desc: String(meta.desc || '').trim(),
      author: String(meta.author || '').trim(),
      sort: Number(meta.sort) || 0,
    })
  }

  out.sort((a, b) => (a.sort - b.sort) || a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }))
  return out
}

function renderCell(item) {
  const base = `./templates/${encodeURI(item.id)}/`
  const cover = `${base}cover.png`
  let html = '<td align="center" valign="top" width="33%">'
  html += `<a href="${base}" style="${LINK_STYLE}">`
  html += `<span style="${FRAME_STYLE}">`
  html += `<img src="${cover}" height="${COVER_H}" alt="${escHtml(item.name)}" style="${IMG_STYLE}">`
  html += '</span><br>'
  html += `<strong>${escHtml(item.name)}</strong></a>`
  if (item.desc) html += `<br>${escHtml(item.desc)}`
  if (item.author) html += `<br><em>by ${escHtml(item.author)}</em>`
  html += '</td>'
  return html
}

function renderGallery(items) {
  if (!items.length) return '_No templates yet._'

  const rows = []
  for (let i = 0; i < items.length; i += 3) {
    const chunk = items.slice(i, i + 3)
    while (chunk.length < 3) chunk.push(null)
    const cells = chunk.map((it) => (it ? renderCell(it) : '<td width="33%"></td>'))
    rows.push(`<tr>${cells.join('\n')}</tr>`)
  }

  return [
    '<!-- Generated by npm run gallery. Do not edit manually. -->',
    `<p><sub>${items.length} template${items.length === 1 ? '' : 's'}</sub></p>`,
    '<table>',
    ...rows,
    '</table>',
  ].join('\n')
}

function patchReadme(gallery) {
  if (!fs.existsSync(readmePath)) {
    throw new Error(`README not found: ${readmePath}`)
  }
  const raw = fs.readFileSync(readmePath, 'utf8')
  const start = raw.indexOf(MARK_START)
  const end = raw.indexOf(MARK_END)
  if (start < 0 || end < 0 || end <= start) {
    throw new Error(`Missing ${MARK_START} / ${MARK_END} in README.md`)
  }

  const head = raw.slice(0, start + MARK_START.length)
  const tail = raw.slice(end)
  const next = `${head}\n\n${gallery}\n\n${tail}`
  fs.writeFileSync(readmePath, next)
}

const items = listTemplates()
const gallery = renderGallery(items)
patchReadme(gallery)
console.log(`Gallery updated: ${items.length} template(s) → README.md`)
